version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/agent"
    schedule:
      interval: "weekly"
    groups:
      agent-go-deps:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/server"
    schedule:
      interval: "weekly"
    groups:
      server-go-deps:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/common"
    schedule:
      interval: "weekly"
    groups:
      common-go-deps:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      root-npm-deps:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/cloudflare-worker"
    schedule:
      interval: "weekly"
    groups:
      cloudflare-worker-npm-deps:
        patterns:
          - "*"
